// web/src/lib/components/AppSidebar.svelte
<script>
    import { House } from "@lucide/svelte";
    import {
        Sidebar,
        SidebarContent,
        SidebarFooter,
        SidebarHeader,
        SidebarMenu,
        SidebarMenuButton,
        SidebarMenuItem,
    } from "./ui/sidebar";
</script>

<Sidebar collapsible="icon">
    <SidebarHeader></SidebarHeader>
    <SidebarContent>
        <SidebarMenu>
            <SidebarMenuItem>
                <SidebarMenuButton class="m-auto">
                    <House />
                    Home
                </SidebarMenuButton>
            </SidebarMenuItem>
        </SidebarMenu>
    </SidebarContent>
    <SidebarFooter></SidebarFooter>
</Sidebar>

// web/src/components/AppSidebar.tsx
import { HouseIcon } from "@phosphor-icons/react";
import { Link } from "react-router-dom";
import {
  Sidebar,
  SidebarContent,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
} from "./ui/sidebar";

export function AppSidebar() {
  return (
    <Sidebar collapsible="icon">
      <SidebarContent className="p-2">
        <SidebarMenu>
          <SidebarMenuItem>
            <SidebarMenuButton className="rounded-lg" asChild>
              <Link to="/">
                <HouseIcon />
                <span>Home</span>
              </Link>
            </SidebarMenuButton>
          </SidebarMenuItem>
        </SidebarMenu>
      </SidebarContent>
    </Sidebar>
  );
}
